### ISSUE TITLE
2.16.0-jp-6 version prediffer ignorecolumns _ 1 - 6 _ 73 - 80.dll does not work

### ISSUE THREAD

**Issue by chaatvedt** [sdottaka/winmerge-v2-jp#4]
I tested with 2.16.0-jp-3 version and it worked correctly

**Comment by sdottaka** [comment]
I could not reproduce the bug. Could you provide the result when selecting [Help]->[Configuration] menu item?

**Comment by sdottaka** [comment]
I can't reproduce it, and I don't know how to reproduce it, so I'll close this issue.
If you know how to reproduce it, please reopen it.
