### ISSUE TITLE
Error comparing subfolders using context menu

### ISSUE THREAD

**Issue by JaegerFox** [sdottaka/winmerge-v2-jp#9]
when I select 2 folders or more the scan only works with the files in the parent folders, but turning off and turning on again the "include subfolders" option works as it should
I'm using the portable version with the ini file in case that helps

**Comment by sdottaka** [comment]
I couldn't reproduce this issue.
Did you hold down the Ctrl key and click the WinMerge menu item in the Explorer context menu? If so, it behaves the same as when the Include Subfolders were unchecked.

**Comment by JaegerFox** [comment]
I did not know that when giving ctrl and clicking it works that way, 
please change the method that by default when clicking works with the last selected options?

**Comment by sdottaka** [comment]
I will see if I can disable the Ctrl key action.
By the way, am I correct in my understanding that not pressing the Ctrl key solved this problem?

**Comment by JaegerFox** [comment]
pressing the ctrl key works as it should...
Could you close this issue if you want
